export const ROOM_TYPES = [
  'Partout', 'Parties communes', 'Cave', 'Chambre', 'Couloir', 'Cuisine', 'Salle de bains', 'Salon', 'Toilettes',
] as const

export const SURFACE_TYPES = [
  'Crédence',
  'Escalier',
  'Évier',
  'Fenêtre (vitre, cadre, poignée)',
  'Interrupteurs',
  'Lavabo (y compris robinetterie et joints)',
  'Mur',
  'Plafond',
  'Plafonnier (Ampoule + Douille)',
  'Point lumière',
  'Porte (y compris cadre, poignée)',
  'Prise câble',
  'Prise Fibre',
  'Prise RJ45',
  'Prise téléphone',
  'Prise télévision',
  'Prises électriques',
  'Rampe',
  'Rembarde',
  'Robinetterie',
  'Sol',
  'Spot 1 lumière',
  'Spot 2 lumières',
  'Spot 3 lumières',
  'Tableau électrique',
  'Trappe de visite',
  'Ventilation',
  "WC (y compris chasse d'eau, joints et abattant)",
] as const

export const SURFACE_MATERIALS = [
  'Bois',
  'Carrelage/faïence',
  'Contreplaqué',
  'Inox',
  'Lambris',
  'Parquet',
  'Parquet peint',
  'Peinture',
  'Plastique',
  'PVC',
  'Verre',
  'Vinyle',
] as const
