-- Ajout des colonnes de catégorisation à transactions_linxo
ALTER TABLE transactions_linxo
  ADD COLUMN IF NOT EXISTS supplier    TEXT,
  ADD COLUMN IF NOT EXISTS type        TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS apartment_num TEXT,
  ADD COLUMN IF NOT EXISTS tenant_name TEXT,
  ADD COLUMN IF NOT EXISTS validated   BOOLEAN NOT NULL DEFAULT FALSE;

-- Table de mappings libellé → type + fournisseur
CREATE TABLE IF NOT EXISTS linxo_mappings (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  libelle_pattern TEXT NOT NULL,
  type            TEXT NOT NULL,
  supplier        TEXT NOT NULL,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Index pour la recherche ILIKE
CREATE INDEX IF NOT EXISTS linxo_mappings_pattern_idx ON linxo_mappings (libelle_pattern);

-- Seed des mappings (ON CONFLICT DO NOTHING via unicité fonctionnelle)
-- On utilise INSERT … WHERE NOT EXISTS pour éviter les doublons au re-run
INSERT INTO linxo_mappings (libelle_pattern, type, supplier) VALUES
  ('1 ET 1',                                          'SERVICES',  '1 ET 1'),
  ('1et1 IONOS',                                      'SERVICES',  '1et1 IONOS'),
  ('ACTION',                                          'ACHAT',     'ACTION'),
  ('ALAIN',                                           'INTERNE',   'ALAIN'),
  ('ALAOUI M HAMMEDI',                                'INTERNE',   'INTERNE'),
  ('AMARRIM',                                         'GESTION',   'AMARRIM'),
  ('AMAZON',                                          'ACHAT',     'AMAZON'),
  ('AUCHAN',                                          'ACHAT',     'AUCHAN'),
  ('AVANTAGE VISA PREMIER',                           'SERVICES',  'LA BANQUE POSTALE'),
  ('BackMarket',                                      'ACHAT',     'BACKMARKET'),
  ('BOUCHARA',                                        'ACHAT',     'BOUCHARA'),
  ('BOULANGER',                                       'ACHAT',     'BOULANGER'),
  ('BOUYGTEL',                                        'SERVICES',  'BOUYGUES TELECOM'),
  ('Bouygues Telecom',                                'SERVICES',  'BOUYGUES TELECOM'),
  ('BOUYGUES TELECOM',                                'SERVICES',  'BOUYGUES TELECOM'),
  ('BRICO DEPOT',                                     'ACHAT',     'BRICO DEPOT'),
  ('BUBBLE',                                          'ACHAT',     'BUBBLE'),
  ('BUT',                                             'ACHAT',     'BUT'),
  ('C EST 2 EUROS',                                   'ACHAT',     'C EST 2 EUROS'),
  ('c est 2 euros',                                   'ACHAT',     'C EST 2 EUROS'),
  ('c''est 2 euros',                                  'ACHAT',     'C EST 2 EUROS'),
  ('C''est Deux Euros',                               'ACHAT',     'C EST 2 EUROS'),
  ('CARGLASS MAISON',                                 'ENTRETIEN', 'CARGLASS MAISON / REPARTIM'),
  ('REPARTIM',                                        'ENTRETIEN', 'CARGLASS MAISON / REPARTIM'),
  ('Carrefour',                                       'ACHAT',     'Carrefour'),
  ('CDISCOUNT',                                       'ACHAT',     'CDISCOUNT'),
  ('CGA NORD-OUEST',                                  'GESTION',   'CGA NORD-OUEST'),
  ('CGANO',                                           'GESTION',   'CGA NORD-OUEST'),
  ('CGALA',                                           'GESTION',   'CGALA'),
  ('CHARLOTTE',                                       'INTERNE',   'CHARLOTTE'),
  ('CHEQUE N',                                        'TRAVAUX',   'INTERNE'),
  ('CLEF STYLE',                                      'TRAVAUX',   'CLEF STYLE'),
  ('CONFORAMA',                                       'ACHAT',     'CONFORAMA'),
  ('DA COSTA MS BAT',                                 'TRAVAUX',   'DA COSTA MS BAT'),
  ('DARTY',                                           'ACHAT',     'DARTY'),
  ('DAVID GUILBERT',                                  'TRAVAUX',   'DAVID GUILBERT'),
  ('DEPS',                                            'ENTRETIEN', 'DEPS'),
  ('DIRECTION GENERAL ES FINANCES PUBL',              'IMPOTS',    'ETAT'),
  ('DOCUSIGN',                                        'ACHAT',     'DOCUSIGN'),
  ('E.LECLERC',                                       'ACHAT',     'E.LECLERC'),
  ('ECH PRET',                                        'SERVICES',  'LA BANQUE POSTALE'),
  ('ECHEANCE PRET',                                   'PRET',      'LA BANQUE POSTALE'),
  ('EDF',                                             'SERVICES',  'EDF'),
  ('EURL POINT SERVICES',                             'ACHAT',     'EURL POINT SERVICES'),
  ('EURODIF',                                         'ACHAT',     'EURODIF'),
  ('FIYO',                                            'ACHAT',     'FIYO'),
  ('FNACMARKETPLAC',                                  'ACHAT',     'FNAC'),
  ('FORMULE DE COMPTE',                               'SERVICES',  'LA BANQUE POSTALE'),
  ('GOOGLE',                                          'ACHAT',     'DOCUSIGN'),
  ('GREAUME JB',                                      'TRAVAUX',   'GREAUME JB - EMBM MENUISERIE'),
  ('Greenweez',                                       'ACHAT',     'Greenweez'),
  ('GUILBERT P',                                      'TRAVAUX',   'PLOMBIER GUILBERT'),
  ('GUILBERT FREDERIC',                               'TRAVAUX',   'PLOMBIER GUILBERT'),
  ('H2ZAEAU PLOMBIER',                                'TRAVAUX',   'H2ZEAU'),
  ('H2ZEAU',                                          'TRAVAUX',   'H2ZEAU'),
  ('HEATZY',                                          'ACHAT',     'HEATZY'),
  ('HEMA',                                            'ACHAT',     'HEMA'),
  ('ID MARKET',                                       'ACHAT',     'ID MARKET'),
  ('IKEA',                                            'ACHAT',     'IKEA'),
  ('INTERMARCHE',                                     'ACHAT',     'INTERMARCHE'),
  ('SAS MAGIN',                                       'ACHAT',     'INTERMARCHE'),
  ('IONOS',                                           'SERVICES',  'IONOS'),
  ('KRAIEM',                                          'SERVICES',  'KRAIEM'),
  ('LA CHAISE LONG',                                  'ACHAT',     'LA CHAISE LONGUE'),
  ('LA PLATEFORME DU BATIMENT',                       'ACHAT',     'LA PLATEFORME DU BATIMENT'),
  ('LA PLATEFORME',                                   'ACHAT',     'LA PLATEFORME DU BATIMENT'),
  ('LA POSTE',                                        'ACHAT',     'LA POSTE'),
  ('LA REDOUTE',                                      'ACHAT',     'LA REDOUTE'),
  ('REDOUTE',                                         'ACHAT',     'LA REDOUTE'),
  ('LANTERI SEBASTIEN',                               'TRAVAUX',   'LANTERI SEBASTIEN'),
  ('LC AGENDADIAGN',                                  'SERVICES',  'AGENDA DIAGNOSTIC'),
  ('LC PRO SERVICE',                                  'TRAVAUX',   'LC PRO SERVICE (SERRURIER)'),
  ('LEROY MER',                                       'ACHAT',     'LEROY MERLIN'),
  ('LEROY MERLIN',                                    'ACHAT',     'LEROY MERLIN'),
  ('MADE.COM',                                        'ACHAT',     'MADE.COM'),
  ('MAGASIN U',                                       'ACHAT',     'MAGASIN U'),
  ('MANO MANO',                                       'ACHAT',     'MANO MANO'),
  ('MANOMANO',                                        'ACHAT',     'MANO MANO'),
  ('MENSUALITE PRET PERSONNEL',                       'PRET',      'LA BANQUE POSTALE'),
  ('MONOPRIX',                                        'ACHAT',     'MONOPRIX'),
  ('NATHALIE DUVAL COMPTABLE',                        'GESTION',   'NATHALIE DUVAL COMPTABLE'),
  ('NEUFTEX',                                         'ACHAT',     'TOTO SOLDES'),
  ('OUTILONLINE',                                     'ACHAT',     'OUTILONLINE'),
  ('PAINTCOST',                                       'TRAVAUX',   'PAINTCOST'),
  ('PAYPAL',                                          'ACHAT',     'PAYPAL'),
  ('PHOTOWEB',                                        'ACHAT',     'PHOTOWEB'),
  ('PLANTES ADDICT',                                  'ACHAT',     'PLANTES ADDICT'),
  ('PLUMBI',                                          'ENTRETIEN', 'PLUMBI'),
  ('PREL DE DIRECTION GENERALE',                      'IMPOTS',    'ETAT'),
  ('Prieur SAS',                                      'TRAVAUX',   'SAS PRIEUR'),
  ('RENTOKIL',                                        'ENTRETIEN', 'RENTOKIL'),
  ('RETRAIT DAB',                                     'INTERNE',   'INTERNE'),
  ('SAILLARD',                                        'TRAVAUX',   'SAILLARD'),
  ('SARL MONNAIE',                                    'TRAVAUX',   'SARL MONNAIE'),
  ('SAS PRIEUR',                                      'TRAVAUX',   'SAS PRIEUR'),
  ('SCP QUESNE MALET',                                'GESTION',   'SCP QUESNE MALET'),
  ('SDC 7 RUE DU MOULINET',                           'TRAVAUX',   'SDC 7 RUE DU MOULINET'),
  ('SELARL ACTAREC',                                  'SERVICES',  'SELARL ACTAREC - HUISSIER LEGER'),
  ('SHOWROOMPRIVE',                                   'ACHAT',     'SHOWROOMPRIVE'),
  ('SKLUM',                                           'ACHAT',     'SKLUM'),
  ('SOFINCO',                                         'PRET',      'SOFINCO'),
  ('SOMEDEC',                                         'TRAVAUX',   'SOMEDEC'),
  ('SOSTRENE GRENE',                                  'ACHAT',     'SOSTRENE GRENE'),
  ('SPRINT',                                          'ACHAT',     'COPYFAC'),
  ('COPIFAC',                                         'ACHAT',     'COPYFAC'),
  ('TAK O TAK',                                       'ACHAT',     'TAK O TAK'),
  ('THELEM',                                          'SERVICES',  'THELEM'),
  ('THOUMYRE',                                        'ACHAT',     'THOUMYRE'),
  ('TOP DECO',                                        'ACHAT',     'TOP DECO'),
  ('TOP RENO',                                        'TRAVAUX',   'TOP RENO'),
  ('TOTO SOLDES',                                     'ACHAT',     'TOTO SOLDES'),
  ('TRES.  ROUEN METR',                               'SERVICES',  'CREA'),
  ('TRES. ROUEN METR',                                'SERVICES',  'CREA'),
  ('TRESORERIE ROUEN',                                'SERVICES',  'CREA'),
  ('SGC ROUEN',                                       'SERVICES',  'CREA'),
  ('VATINE GEOFFREY',                                 'TRAVAUX',   'VATINE GEOFFREY'),
  ('Vattenfall',                                      'SERVICES',  'Vattenfall'),
  ('VENTE PRIVEE',                                    'ACHAT',     'VENTE PRIVEE'),
  ('VENTE-PRIVEE',                                    'ACHAT',     'VENTE PRIVEE'),
  ('VP.COM',                                          'ACHAT',     'VENTE PRIVEE'),
  ('WORLDPAY',                                        'ACHAT',     'DOCUSIGN'),
  ('ZEEMAN',                                          'ACHAT',     'ZEEMAN'),
  ('4 MURS',                                          'ACHAT',     '4 MURS'),
  ('PEARL DIFFUSIO',                                  'ACHAT',     'PEARL DIFFUSION'),
  ('BLEU CALIN',                                      'ACHAT',     'BLEU CALIN'),
  ('SFR',                                             'SERVICES',  'SFR'),
  ('VIREMENT PERMANENT POUR MME ALAOUI M HAMMEDI',    'INTERNE',   'INTERNE'),
  ('Temu.com',                                        'ACHAT',     'TEMU'),
  ('BRICOLO',                                         'ACHAT',     'MR BRICOLAGE'),
  ('ELEC3F',                                          'TRAVAUX',   'ELEC3F'),
  ('ROBOROCK',                                        'ACHAT',     'ROBOROCK'),
  ('MILIBOO',                                         'ACHAT',     'MILIBOO')
ON CONFLICT DO NOTHING;
